[package]
name = "pus_serializer_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-space-core = { path = "../rs-space-core" }
serde_json = "1"
serde_yaml = "0.9.13"