[package]
name = "cnc_receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-space-core = { path = "../rs-space-core" }
tokio = { version = "1.21.0", features = [ "full" ] }
